# Generated by Django 4.2 on 2025-09-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersfavoritemovies',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='usersfavoritemovies',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='unique_user_movie'),
        ),
    ]
