# Generated by Django 4.2 on 2025-09-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usersfavoritemovies_unique_together_and_more'),
    ]

    operations = [
    ]
