# Generated by Django 4.2 on 2025-09-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250901_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='sdt',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
