# Generated by Django 4.2 on 2025-09-04 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_slug'),
        ('users', '0004_users_sdt'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersCommentMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_comments', to='users.users')),
            ],
            options={
                'db_table': 'users_comment_movies',
                'ordering': ['-created_at'],
            },
        ),
    ]
