# Generated by Django 4.2 on 2025-08-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='nomination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='titleE',
            field=models.CharField(default='No Title', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(default='No Title', max_length=255),
        ),
    ]
