# Generated by Django 4.2 on 2025-11-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='series',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
